/**
 * XPO MICE Ecosystem: Fallback Datasets for Discovery Engine & Venue Hubs
 *
 * Provides realistic MICE venues with exact hall specifications, transit guides,
 * and multi-archetype exhibitions matching the Prisma seed schema.
 */

import { type DiscoveryEvent, type VenueSummary, type BannerSlide } from '@/types/discovery';

export const FALLBACK_VENUES: VenueSummary[] = [
  {
    id: 'venue-jiexpo',
    name: 'JIExpo Kemayoran (Jakarta International Expo)',
    slug: 'jiexpo-kemayoran',
    city: 'Central Jakarta',
    address: 'Gedung Pusat Niaga Lt. 1, Arena JIEXPO Kemayoran, RW.10, Pademangan Tim., Jakarta Pusat',
    latitude: -6.1466,
    longitude: 106.8454,
    regionId: 'id',
    region: { id: 'id', code: 'ID', name: 'Indonesia', currency: 'IDR' },
    transitInfo: 'TransJakarta Corridor 2C (Monas - JIExpo) & 12M. KRL Stasiun Rajawali (7 mins walk) & Stasiun Kemayoran. Dedicated shuttle at Gate 2.',
    imageUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200',
    halls: [
      { id: 'jiexpo-a1', name: 'Hall A1-A3 (Heavy Machinery)', capacity: 12000, floorAreaSqm: 10500, description: 'Reinforced flooring for industrial machinery and heavy automotive displays.' },
      { id: 'jiexpo-b1', name: 'Hall B1-B3 (Consumer & Electronics)', capacity: 8500, floorAreaSqm: 8000, description: 'Multi-level consumer trade show and electronics pavilion.' },
      { id: 'jiexpo-c1', name: 'Hall C1-C3 (B2B Procurement)', capacity: 7000, floorAreaSqm: 6500, description: 'Dedicated B2B sourcing booths and meeting cubicles.' },
      { id: 'jiexpo-d1', name: 'Hall D1-D2 (Grand Exhibition Hall)', capacity: 15000, floorAreaSqm: 11000, description: 'Column-free mega hall with 14m ceiling height.' },
      { id: 'jiexpo-ballroom', name: 'Grand Ballroom', capacity: 3500, floorAreaSqm: 3000, description: 'Luxury banquet and plenary keynote stage.' },
      { id: 'jiexpo-open', name: 'Open Space Arena', capacity: 45000, floorAreaSqm: 35000, description: 'Massive open-air festival ground for Jakarta Fair & live music.' },
    ],
  },
  {
    id: 'venue-ice',
    name: 'ICE BSD City (Indonesia Convention Exhibition)',
    slug: 'ice-bsd-city',
    city: 'Tangerang / BSD City',
    address: 'Jl. BSD Grand Boulevard No.1, Pagedangan, Kec. Pagedangan, Kabupaten Tangerang, Banten',
    latitude: -6.3023,
    longitude: 106.6372,
    regionId: 'id',
    region: { id: 'id', code: 'ID', name: 'Indonesia', currency: 'IDR' },
    transitInfo: 'BSD Link Free Shuttle from Intermoda BSD. KRL Commuter Line Stasiun Rawa Buntu & Cisauk. Toll Serbaraja Exit ICE BSD.',
    imageUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=1200',
    halls: [
      { id: 'ice-h1-3', name: 'Hall 1 - 3 (Industrial & Tech)', capacity: 18000, floorAreaSqm: 15000, description: 'Connected column-free halls for massive trade exhibitions.' },
      { id: 'ice-h5-7', name: 'Hall 5 - 7 (International Pavilions)', capacity: 18000, floorAreaSqm: 15000, description: 'Global country booths and innovation showcases.' },
      { id: 'ice-h8-10', name: 'Hall 8 - 10 (Arena Stage)', capacity: 20000, floorAreaSqm: 15000, description: 'Equipped for arena concerts and major esports tournaments.' },
      { id: 'ice-nusantara', name: 'Nusantara Hall 2', capacity: 4000, floorAreaSqm: 4000, description: 'State-of-the-art acoustic convention hall for tech keynotes.' },
      { id: 'ice-conv', name: 'Convention Hall 1-3', capacity: 3000, floorAreaSqm: 3000, description: 'Acoustic partitioned halls for medical symposia.' },
    ],
  },
  {
    id: 'venue-jcc',
    name: 'JICC (Jakarta International Convention Center / Balai Sidang)',
    slug: 'jcc-senayan',
    city: 'Central Jakarta',
    address: 'Jl. Gatot Subroto No.1, Gelora, Kecamatan Tanah Abang, Kota Jakarta Pusat',
    latitude: -6.2146,
    longitude: 106.8066,
    regionId: 'id',
    region: { id: 'id', code: 'ID', name: 'Indonesia', currency: 'IDR' },
    transitInfo: 'MRT Jakarta Stasiun Istora Mandiri (5 mins walkway). TransJakarta Corridor 9 & 1 JCC Senayan.',
    imageUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1200',
    halls: [
      { id: 'jcc-plenary', name: 'Plenary Hall', capacity: 5000, floorAreaSqm: 4500, description: 'Iconic auditorium for presidential keynotes and medical congresses.' },
      { id: 'jcc-assembly', name: 'Assembly Hall', capacity: 3000, floorAreaSqm: 3200, description: 'Diplomatic delegations and formal gala assemblies.' },
      { id: 'jcc-hall-a', name: 'Exhibition Hall A', capacity: 6000, floorAreaSqm: 5500, description: 'Trade show floor connecting to Senayan hospitality suites.' },
      { id: 'jcc-hall-b', name: 'Exhibition Hall B', capacity: 7000, floorAreaSqm: 6000, description: 'Direct truck access for commercial expos.' },
      { id: 'jcc-cendrawasih', name: 'Cendrawasih Room', capacity: 1800, floorAreaSqm: 2000, description: 'Acoustic scientific paper presentation rooms.' },
    ],
  },
  {
    id: 'venue-nice',
    name: 'NICE PIK 2 (Nusantara International Convention Exhibition)',
    slug: 'nice-pik-2',
    city: 'Tangerang / PIK 2',
    address: 'Kawasan PIK 2 Waterfront City, Kosambi, Tangerang, Banten',
    latitude: -6.0792,
    longitude: 106.7265,
    regionId: 'id',
    region: { id: 'id', code: 'ID', name: 'Indonesia', currency: 'IDR' },
    transitInfo: 'PIK 2 Express Shuttle from Pluit & Muara Karang. Direct Toll Interchange PIK 2.',
    imageUrl: 'https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?w=1200',
    halls: [
      { id: 'nice-h1-8', name: 'Exhibition Halls 1 - 8', capacity: 35000, floorAreaSqm: 30000, description: 'Next-gen ultra-modern sustainable trade complex.' },
      { id: 'nice-ballroom', name: 'Grand Ballroom PIK 2', capacity: 5000, floorAreaSqm: 4500, description: 'Luxury waterfront executive galas.' },
      { id: 'nice-atrium', name: 'Atrium Central', capacity: 8000, floorAreaSqm: 6000, description: 'Natural light architectural center atrium.' },
    ],
  },
  {
    id: 'venue-tokyo',
    name: 'Tokyo Big Sight (Tokyo International Exhibition Center)',
    slug: 'tokyo-big-sight',
    city: 'Tokyo (Koto Ward)',
    address: '3-11-1 Ariake, Koto City, Tokyo 135-0063, Japan',
    latitude: 35.6298,
    longitude: 139.7942,
    regionId: 'jp',
    region: { id: 'jp', code: 'JP', name: 'Japan', currency: 'JPY' },
    transitInfo: 'Yurikamome Line (Tokyo Big Sight Station, 3 mins). Rinkai Line (Kokusai-Tenjijo Station, 7 mins). Water Bus Ariake Terminal.',
    imageUrl: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200',
    halls: [
      { id: 'tokyo-east', name: 'East Exhibition Halls 1-8', capacity: 40000, floorAreaSqm: 38000, description: 'Japan largest exhibition hall complex.' },
      { id: 'tokyo-west', name: 'West Exhibition Halls 1-4', capacity: 25000, floorAreaSqm: 22000, description: 'Atrium-connected multi-tier tech halls.' },
      { id: 'tokyo-south', name: 'South Exhibition Halls 1-4', capacity: 22000, floorAreaSqm: 20000, description: 'Ultra-modern robotics and AI conference facilities.' },
      { id: 'tokyo-tower', name: 'Conference Tower (Inverted Pyramid)', capacity: 5000, floorAreaSqm: 6000, description: 'International symposiums and executive committee rooms.' },
    ],
  },
  {
    id: 'venue-mbs',
    name: 'Marina Bay Sands Expo & Convention Centre',
    slug: 'marina-bay-sands-expo',
    city: 'Singapore',
    address: '10 Bayfront Ave, Singapore 018956',
    latitude: 1.2838,
    longitude: 103.8591,
    regionId: 'global',
    region: { id: 'global', code: 'GL', name: 'Global Hubs', currency: 'USD' },
    transitInfo: 'MRT Bayfront Station (Circle & Downtown Lines direct basement exit).',
    imageUrl: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=1200',
    halls: [
      { id: 'mbs-halls', name: 'Sands Expo Halls A-F (Basement 2)', capacity: 20000, floorAreaSqm: 30000, description: 'Integrated flexible trade hall.' },
      { id: 'mbs-ballroom', name: 'Grand Ballroom Level 5 (Sands Grand)', capacity: 8000, floorAreaSqm: 8000, description: 'Southeast Asia largest ballroom.' },
    ],
  },
];

export const FALLBACK_EVENTS: DiscoveryEvent[] = [
  {
    id: 'event-mfg-2026',
    title: 'Manufacturing Indonesia & Industrial Automation Expo 2026',
    slug: 'manufacturing-indonesia-2026',
    tagline: 'The 36th International Manufacturing, Machinery, Equipment & Materials Exhibition',
    description: 'Southeast Asia premier industrial gathering. Live demonstrations of CNC robotics, metallurgy, smart factory automation, and heavy machine tools with 1,500 global exhibitors.',
    archetype: 'INDUSTRIAL_B2B',
    startDate: new Date('2026-09-14T09:00:00Z'),
    endDate: new Date('2026-09-17T18:00:00Z'),
    isFeatured: true,
    scale: 'LARGE',
    format: 'IN_PERSON',
    heroImageUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=1200',
    regionId: 'id',
    region: { id: 'id', code: 'ID', name: 'Indonesia', currency: 'IDR' },
    venueId: 'venue-jiexpo',
    venue: FALLBACK_VENUES[0],
    ticketTiers: [
      { id: 'tier-mfg-visitor', name: 'Trade Visitor Pass', price: 0, currency: 'IDR', capacity: 15000 },
      { id: 'tier-mfg-vip', name: 'VIP Procurement Buyer Pass', price: 450000, currency: 'IDR', capacity: 1200 },
      { id: 'tier-mfg-exhibitor', name: 'Exhibitor Delegate Pass', price: 1200000, currency: 'IDR', capacity: 3000 },
    ],
  },
  {
    id: 'event-ai-summit-2026',
    title: 'Asia AI & Cloud Developer Summit 2026',
    slug: 'asia-ai-summit-2026',
    tagline: 'Building Autonomous Multi-Agent Systems, LLMs & Next-Gen Cloud Infrastructure',
    description: 'Asia premier technical gathering for software engineers, AI researchers, and cloud architects with deep-dive keynotes, live code teardowns, and a 24-hour hackathon.',
    archetype: 'TECH_DEV_SUMMIT',
    startDate: new Date('2026-10-08T08:30:00Z'),
    endDate: new Date('2026-10-10T20:00:00Z'),
    isFeatured: true,
    scale: 'LARGE',
    format: 'HYBRID',
    heroImageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200',
    regionId: 'id',
    region: { id: 'id', code: 'ID', name: 'Indonesia', currency: 'IDR' },
    venueId: 'venue-ice',
    venue: FALLBACK_VENUES[1],
    ticketTiers: [
      { id: 'tier-ai-builder', name: 'Builder Pass', price: 250000, currency: 'IDR', capacity: 4000 },
      { id: 'tier-ai-vip', name: 'VIP Full Access & Speaker Dinner', price: 1250000, currency: 'IDR', capacity: 500 },
      { id: 'tier-ai-virtual', name: 'Virtual Livestream Pass', price: 0, currency: 'IDR', capacity: 20000 },
    ],
  },
  {
    id: 'event-prj-2026',
    title: 'Pekan Raya Jakarta (Jakarta Fair Kemayoran 2026)',
    slug: 'pekan-raya-jakarta-2026',
    tagline: 'The Largest & Longest-Running Consumer Mega Fair in Southeast Asia',
    description: 'Celebrate Jakarta anniversary with 33 consecutive days of mega consumer expositions, 500+ culinary tenants, massive automotive launches, nightly open-air concerts, and grand fireworks.',
    archetype: 'MEGA_EXPO_PAVILION',
    startDate: new Date('2026-06-10T10:00:00Z'),
    endDate: new Date('2026-07-12T23:00:00Z'),
    isFeatured: true,
    scale: 'GLOBAL_MEGA',
    format: 'IN_PERSON',
    heroImageUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1200',
    regionId: 'id',
    region: { id: 'id', code: 'ID', name: 'Indonesia', currency: 'IDR' },
    venueId: 'venue-jiexpo',
    venue: FALLBACK_VENUES[0],
    ticketTiers: [
      { id: 'tier-prj-entry', name: 'General Fair Entry (Non-Concert)', price: 40000, currency: 'IDR', capacity: 100000 },
      { id: 'tier-prj-concert', name: 'Fair Entry + Main Concert Pass', price: 100000, currency: 'IDR', capacity: 25000 },
      { id: 'tier-prj-vip', name: 'Season VIP Mega Pass (33 Days)', price: 650000, currency: 'IDR', capacity: 2500 },
    ],
  },
  {
    id: 'event-tokyo-robotics-2026',
    title: 'Tokyo International Robotics & Mechatronics Expo 2026',
    slug: 'tokyo-robotics-expo-2026',
    tagline: 'Humanoid Robotics, Autonomous Mobility & Industrial AI Automation',
    description: 'The world foremost robotics exhibition held at Tokyo Big Sight East Halls. Discover breakthrough humanoid robots, collaborative arms, surgical mechatronics, and autonomous factory logistics.',
    archetype: 'TECH_DEV_SUMMIT',
    startDate: new Date('2026-11-18T10:00:00Z'),
    endDate: new Date('2026-11-21T17:00:00Z'),
    isFeatured: true,
    scale: 'LARGE',
    format: 'IN_PERSON',
    heroImageUrl: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=1200',
    regionId: 'jp',
    region: { id: 'jp', code: 'JP', name: 'Japan', currency: 'JPY' },
    venueId: 'venue-tokyo',
    venue: FALLBACK_VENUES[4],
    ticketTiers: [
      { id: 'tier-tokyo-gen', name: 'General Trade Pass', price: 3000, currency: 'JPY', capacity: 30000 },
      { id: 'tier-tokyo-vip', name: 'Executive Delegate & Lab Tour', price: 15000, currency: 'JPY', capacity: 2000 },
    ],
  },
  {
    id: 'event-singapore-fintech-2026',
    title: 'Global FinTech & Institutional Investment Summit 2026',
    slug: 'singapore-fintech-summit-2026',
    tagline: 'Cross-Border Capital, Sovereign Wealth & AI-Driven Asset Management',
    description: 'High-level financial assembly bringing together central bank governors, institutional investors, sovereign wealth funds, and leading fintech innovators at Marina Bay Sands.',
    archetype: 'FINANCE_INVESTOR',
    startDate: new Date('2026-11-04T09:00:00Z'),
    endDate: new Date('2026-11-06T18:00:00Z'),
    isFeatured: true,
    scale: 'LARGE',
    format: 'HYBRID',
    heroImageUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=1200',
    regionId: 'global',
    region: { id: 'global', code: 'GL', name: 'Global Hubs', currency: 'USD' },
    venueId: 'venue-mbs',
    venue: FALLBACK_VENUES[5],
    ticketTiers: [
      { id: 'tier-fintech-delegate', name: 'Executive Delegate Pass', price: 495, currency: 'USD', capacity: 2500 },
      { id: 'tier-fintech-vip', name: 'VIP Investor Deal-Room Pass', price: 1250, currency: 'USD', capacity: 400 },
    ],
  },
  {
    id: 'event-medical-symposium-2026',
    title: 'ASEAN International Clinical Oncology & Genomics Congress 2026',
    slug: 'asean-clinical-oncology-2026',
    tagline: 'Precision Oncology, mRNA Therapeutics & CME Accredited Medical Science',
    description: 'Prestigious clinical congress for oncologists, geneticists, and healthcare researchers with peer-reviewed clinical research presentations and CME accreditation.',
    archetype: 'MEDICAL_SYMPOSIUM',
    startDate: new Date('2026-10-22T08:00:00Z'),
    endDate: new Date('2026-10-25T17:00:00Z'),
    isFeatured: false,
    scale: 'MEDIUM',
    format: 'IN_PERSON',
    heroImageUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=1200',
    regionId: 'id',
    region: { id: 'id', code: 'ID', name: 'Indonesia', currency: 'IDR' },
    venueId: 'venue-jcc',
    venue: FALLBACK_VENUES[2],
    ticketTiers: [
      { id: 'tier-med-clinician', name: 'Physician / Clinician Pass (12 CME)', price: 750000, currency: 'IDR', capacity: 1500 },
      { id: 'tier-med-student', name: 'Medical Resident Pass', price: 250000, currency: 'IDR', capacity: 600 },
    ],
  },
];

export const FALLBACK_BANNER_SLIDES: BannerSlide[] = [
  {
    id: 'slide-1',
    title: 'Manufacturing Indonesia & Automation Expo 2026',
    tagline: '36th International Machinery, CNC Tooling & Industrial Robotics Exhibition',
    slug: 'manufacturing-indonesia-2026',
    heroImageUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=1600',
    archetype: 'INDUSTRIAL_B2B',
    startDate: new Date('2026-09-14T09:00:00Z'),
    endDate: new Date('2026-09-17T18:00:00Z'),
    venueName: 'JIExpo Kemayoran',
    cityName: 'Jakarta',
    regionCode: 'ID',
    format: 'IN_PERSON',
    scale: 'LARGE',
    minPrice: 0,
    currency: 'IDR',
    isFeatured: true,
  },
  {
    id: 'slide-2',
    title: 'Asia AI & Cloud Developer Summit 2026',
    tagline: 'Autonomous Multi-Agent Architectures, Edge LLMs & Cloud Engineering Keynotes',
    slug: 'asia-ai-summit-2026',
    heroImageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=1600',
    archetype: 'TECH_DEV_SUMMIT',
    startDate: new Date('2026-10-08T08:30:00Z'),
    endDate: new Date('2026-10-10T20:00:00Z'),
    venueName: 'ICE BSD City',
    cityName: 'Tangerang',
    regionCode: 'ID',
    format: 'HYBRID',
    scale: 'LARGE',
    minPrice: 250000,
    currency: 'IDR',
    isFeatured: true,
  },
  {
    id: 'slide-3',
    title: 'Pekan Raya Jakarta (Jakarta Fair 2026)',
    tagline: '33 Days of Mega Consumer Exhibitions, 500+ Tenants & Nightly Live Concerts',
    slug: 'pekan-raya-jakarta-2026',
    heroImageUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1600',
    archetype: 'MEGA_EXPO_PAVILION',
    startDate: new Date('2026-06-10T10:00:00Z'),
    endDate: new Date('2026-07-12T23:00:00Z'),
    venueName: 'JIExpo Kemayoran',
    cityName: 'Jakarta',
    regionCode: 'ID',
    format: 'IN_PERSON',
    scale: 'GLOBAL_MEGA',
    minPrice: 40000,
    currency: 'IDR',
    isFeatured: true,
  },
];
