/**
 * XPO MICE Ecosystem: Fallback Datasets for Discovery Engine & Regional Hubs
 *
 * Provides realistic MICE venues with exact hall specifications, transit guides,
 * and multi-archetype exhibitions across Indonesia (ID), Japan (JP), and Global Hubs (GL).
 */

import { type DiscoveryEvent, type VenueSummary, type BannerSlide } from '@/types/discovery';

export const FALLBACK_VENUES: VenueSummary[] = [
  // =========================================================================
  // 1. INDONESIA VENUES (ID)
  // =========================================================================
  {
    id: 'venue-jiexpo',
    name: 'JIExpo Kemayoran (Jakarta International Expo)',
    slug: 'jiexpo-kemayoran',
    city: 'Central Jakarta',
    address: 'Gedung Pusat Niaga Lt. 1, Arena JIEXPO Kemayoran, RW.10, Pademangan Tim., Jakarta Pusat',
    latitude: -6.1466,
    longitude: 106.8454,
    regionId: 'id',
    region: { id: 'id', code: 'ID', name: 'Indonesia', currency: 'IDR' },
    transitInfo: 'TransJakarta Corridor 2C (Monas - JIExpo) & 12M. KRL Stasiun Rajawali (7 mins walk) & Stasiun Kemayoran. Dedicated shuttle at Gate 2.',
    imageUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200',
    halls: [
      { id: 'jiexpo-a1', name: 'Hall A1-A3 (Heavy Machinery)', capacity: 12000, floorAreaSqm: 10500, description: 'Reinforced flooring for industrial machinery and heavy automotive displays.' },
      { id: 'jiexpo-b1', name: 'Hall B1-B3 (Consumer & Electronics)', capacity: 8500, floorAreaSqm: 8000, description: 'Multi-level consumer trade show and electronics pavilion.' },
      { id: 'jiexpo-c1', name: 'Hall C1-C3 (B2B Procurement)', capacity: 7000, floorAreaSqm: 6500, description: 'Dedicated B2B sourcing booths and meeting cubicles.' },
      { id: 'jiexpo-d1', name: 'Hall D1-D2 (Grand Exhibition Hall)', capacity: 15000, floorAreaSqm: 11000, description: 'Column-free mega hall with 14m ceiling height.' },
      { id: 'jiexpo-ballroom', name: 'Grand Ballroom', capacity: 3500, floorAreaSqm: 3000, description: 'Luxury banquet and plenary keynote stage.' },
      { id: 'jiexpo-open', name: 'Open Space Arena', capacity: 45000, floorAreaSqm: 35000, description: 'Massive open-air festival ground for Jakarta Fair & live music.' },
    ],
  },
  {
    id: 'venue-ice',
    name: 'ICE BSD City (Indonesia Convention Exhibition)',
    slug: 'ice-bsd-city',
    city: 'Tangerang / BSD City',
    address: 'Jl. BSD Grand Boulevard No.1, Pagedangan, Kec. Pagedangan, Kabupaten Tangerang, Banten',
    latitude: -6.3023,
    longitude: 106.6372,
    regionId: 'id',
    region: { id: 'id', code: 'ID', name: 'Indonesia', currency: 'IDR' },
    transitInfo: 'BSD Link Free Shuttle from Intermoda BSD. KRL Commuter Line Stasiun Rawa Buntu & Cisauk. Toll Serbaraja Exit ICE BSD.',
    imageUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=1200',
    halls: [
      { id: 'ice-h1-3', name: 'Hall 1 - 3 (Industrial & Tech)', capacity: 18000, floorAreaSqm: 15000, description: 'Connected column-free halls for massive trade exhibitions.' },
      { id: 'ice-h5-7', name: 'Hall 5 - 7 (International Pavilions)', capacity: 18000, floorAreaSqm: 15000, description: 'Global country booths and innovation showcases.' },
      { id: 'ice-h8-10', name: 'Hall 8 - 10 (Arena Stage)', capacity: 20000, floorAreaSqm: 15000, description: 'Equipped for arena concerts and major esports tournaments.' },
      { id: 'ice-nusantara', name: 'Nusantara Hall 2', capacity: 4000, floorAreaSqm: 4000, description: 'State-of-the-art acoustic convention hall for tech keynotes.' },
      { id: 'ice-conv', name: 'Convention Hall 1-3', capacity: 3000, floorAreaSqm: 3000, description: 'Acoustic partitioned halls for medical symposia.' },
    ],
  },
  {
    id: 'venue-jcc',
    name: 'JICC (Jakarta International Convention Center / Balai Sidang)',
    slug: 'jcc-senayan',
    city: 'Central Jakarta',
    address: 'Jl. Gatot Subroto No.1, Gelora, Kecamatan Tanah Abang, Kota Jakarta Pusat',
    latitude: -6.2146,
    longitude: 106.8066,
    regionId: 'id',
    region: { id: 'id', code: 'ID', name: 'Indonesia', currency: 'IDR' },
    transitInfo: 'MRT Jakarta Stasiun Istora Mandiri (5 mins walkway). TransJakarta Corridor 9 & 1 JCC Senayan.',
    imageUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1200',
    halls: [
      { id: 'jcc-plenary', name: 'Plenary Hall', capacity: 5000, floorAreaSqm: 4500, description: 'Iconic auditorium for presidential keynotes and medical congresses.' },
      { id: 'jcc-assembly', name: 'Assembly Hall', capacity: 3000, floorAreaSqm: 3200, description: 'Diplomatic delegations and formal gala assemblies.' },
      { id: 'jcc-hall-a', name: 'Exhibition Hall A', capacity: 6000, floorAreaSqm: 5500, description: 'Trade show floor connecting to Senayan hospitality suites.' },
      { id: 'jcc-hall-b', name: 'Exhibition Hall B', capacity: 7000, floorAreaSqm: 6000, description: 'Direct truck access for commercial expos.' },
      { id: 'jcc-cendrawasih', name: 'Cendrawasih Room', capacity: 1800, floorAreaSqm: 2000, description: 'Acoustic scientific paper presentation rooms.' },
    ],
  },
  {
    id: 'venue-nice',
    name: 'NICE PIK 2 (Nusantara International Convention Exhibition)',
    slug: 'nice-pik-2',
    city: 'Tangerang / PIK 2',
    address: 'Kawasan PIK 2 Waterfront City, Kosambi, Tangerang, Banten',
    latitude: -6.0792,
    longitude: 106.7265,
    regionId: 'id',
    region: { id: 'id', code: 'ID', name: 'Indonesia', currency: 'IDR' },
    transitInfo: 'PIK 2 Express Shuttle from Pluit & Muara Karang. Direct Toll Interchange PIK 2.',
    imageUrl: 'https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?w=1200',
    halls: [
      { id: 'nice-h1-8', name: 'Exhibition Halls 1 - 8', capacity: 35000, floorAreaSqm: 30000, description: 'Next-gen ultra-modern sustainable trade complex.' },
      { id: 'nice-ballroom', name: 'Grand Ballroom PIK 2', capacity: 5000, floorAreaSqm: 4500, description: 'Luxury waterfront executive galas.' },
      { id: 'nice-atrium', name: 'Atrium Central', capacity: 8000, floorAreaSqm: 6000, description: 'Natural light architectural center atrium.' },
    ],
  },

  // =========================================================================
  // 2. JAPAN VENUES (JP)
  // =========================================================================
  {
    id: 'venue-tokyo',
    name: 'Tokyo Big Sight (Tokyo International Exhibition Center)',
    slug: 'tokyo-big-sight',
    city: 'Tokyo (Koto Ward)',
    address: '3-11-1 Ariake, Koto City, Tokyo 135-0063, Japan',
    latitude: 35.6298,
    longitude: 139.7942,
    regionId: 'jp',
    region: { id: 'jp', code: 'JP', name: 'Japan', currency: 'JPY' },
    transitInfo: 'Yurikamome Line (Tokyo Big Sight Station, 3 mins). Rinkai Line (Kokusai-Tenjijo Station, 7 mins). Water Bus Ariake Terminal.',
    imageUrl: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200',
    halls: [
      { id: 'tokyo-east', name: 'East Exhibition Halls 1-8', capacity: 40000, floorAreaSqm: 38000, description: 'Japan largest exhibition hall complex.' },
      { id: 'tokyo-west', name: 'West Exhibition Halls 1-4', capacity: 25000, floorAreaSqm: 22000, description: 'Atrium-connected multi-tier tech halls.' },
      { id: 'tokyo-south', name: 'South Exhibition Halls 1-4', capacity: 22000, floorAreaSqm: 20000, description: 'Ultra-modern robotics and AI conference facilities.' },
      { id: 'tokyo-tower', name: 'Conference Tower (Inverted Pyramid)', capacity: 5000, floorAreaSqm: 6000, description: 'International symposiums and executive committee rooms.' },
    ],
  },
  {
    id: 'venue-makuhari',
    name: 'Makuhari Messe International Convention Complex',
    slug: 'makuhari-messe',
    city: 'Chiba / Tokyo Bay',
    address: '2-1 Nakase, Mihama Ward, Chiba, 261-8550, Japan',
    latitude: 35.6483,
    longitude: 140.0347,
    regionId: 'jp',
    region: { id: 'jp', code: 'JP', name: 'Japan', currency: 'JPY' },
    transitInfo: 'JR Keiyo Line (Kaihimmakuhari Station, 5 mins walk). Direct Narita/Haneda Airport Limousine bus.',
    imageUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200',
    halls: [
      { id: 'makuhari-1-8', name: 'International Exhibition Halls 1-8', capacity: 38000, floorAreaSqm: 35000, description: 'High-ceiling column-free halls for Tokyo Game Show.' },
      { id: 'makuhari-event', name: 'Makuhari Event Hall (Arena)', capacity: 9000, floorAreaSqm: 7000, description: 'Oval multipurpose arena for concerts and esports.' },
    ],
  },
  {
    id: 'venue-pacifico',
    name: 'Pacifico Yokohama Convention Center',
    slug: 'pacifico-yokohama',
    city: 'Yokohama (Minato Mirai)',
    address: '1-1-1 Minatomirai, Nishi Ward, Yokohama, Kanagawa 220-0012, Japan',
    latitude: 35.4593,
    longitude: 139.6366,
    regionId: 'jp',
    region: { id: 'jp', code: 'JP', name: 'Japan', currency: 'JPY' },
    transitInfo: 'Minatomirai Line (Minatomirai Station, 5 mins walk). JR Sakuragicho Station (12 mins walk).',
    imageUrl: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=1200',
    halls: [
      { id: 'pacifico-hall', name: 'National Convention Hall of Yokohama', capacity: 5000, floorAreaSqm: 5000, description: 'One of the largest international convention halls in Asia.' },
      { id: 'pacifico-expo', name: 'Exhibition Hall A-D', capacity: 20000, floorAreaSqm: 20000, description: 'Spacious ocean-view exhibition floor.' },
    ],
  },

  // =========================================================================
  // 3. GLOBAL GATEWAY VENUES (GLOBAL)
  // =========================================================================
  {
    id: 'venue-mbs',
    name: 'Marina Bay Sands Expo & Convention Centre',
    slug: 'marina-bay-sands-expo',
    city: 'Singapore',
    address: '10 Bayfront Ave, Singapore 018956',
    latitude: 1.2838,
    longitude: 103.8591,
    regionId: 'global',
    region: { id: 'global', code: 'GL', name: 'Global Hubs', currency: 'USD' },
    transitInfo: 'MRT Bayfront Station (Circle & Downtown Lines direct basement exit).',
    imageUrl: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=1200',
    halls: [
      { id: 'mbs-halls', name: 'Sands Expo Halls A-F (Basement 2)', capacity: 20000, floorAreaSqm: 30000, description: 'Integrated flexible trade hall.' },
      { id: 'mbs-ballroom', name: 'Grand Ballroom Level 5 (Sands Grand)', capacity: 8000, floorAreaSqm: 8000, description: 'Southeast Asia largest ballroom.' },
    ],
  },
  {
    id: 'venue-messe-frankfurt',
    name: 'Messe Frankfurt Exhibition Centre',
    slug: 'messe-frankfurt',
    city: 'Frankfurt am Main, Germany',
    address: 'Ludwig-Erhard-Anlage 1, 60327 Frankfurt am Main, Germany',
    latitude: 50.1115,
    longitude: 8.6515,
    regionId: 'global',
    region: { id: 'global', code: 'GL', name: 'Global Hubs', currency: 'USD' },
    transitInfo: 'S-Bahn lines S3, S4, S5, S6 (Frankfurt Messe Station direct access). Frankfurt Airport 15 mins.',
    imageUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=1200',
    halls: [
      { id: 'frankfurt-hall-12', name: 'Hall 12 (Ultra-Modern Pavilion)', capacity: 25000, floorAreaSqm: 33000, description: 'State-of-the-art dual-level trade exhibition hall.' },
      { id: 'frankfurt-hall-3', name: 'Hall 3 (Automotive Mega Stage)', capacity: 20000, floorAreaSqm: 28000, description: 'Iconic multistory venue for international mobility expos.' },
    ],
  },
  {
    id: 'venue-excel-london',
    name: 'ExCeL London International Convention Centre',
    slug: 'excel-london',
    city: 'London, United Kingdom',
    address: 'Royal Victoria Dock, 1 Western Gateway, London E16 1XL, UK',
    latitude: 51.5074,
    longitude: 0.0298,
    regionId: 'global',
    region: { id: 'global', code: 'GL', name: 'Global Hubs', currency: 'USD' },
    transitInfo: 'Elizabeth Line & DLR Custom House for ExCeL station (12 mins from Central London).',
    imageUrl: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=1200',
    halls: [
      { id: 'excel-icc', name: 'ICC London Auditorium', capacity: 5000, floorAreaSqm: 6000, description: 'UK premier plenary convention theatre.' },
      { id: 'excel-event-halls', name: 'Event Halls North & South', capacity: 35000, floorAreaSqm: 40000, description: 'Continuous column-free international event space.' },
    ],
  },
];

export const FALLBACK_EVENTS: DiscoveryEvent[] = [
  // -------------------------------------------------------------------------
  // INDONESIA EVENTS (ID)
  // -------------------------------------------------------------------------
  {
    id: 'event-mfg-2026',
    title: 'Manufacturing Indonesia & Industrial Automation Expo 2026',
    slug: 'manufacturing-indonesia-2026',
    tagline: 'The 36th International Manufacturing, Machinery, Equipment & Materials Exhibition',
    description: 'Southeast Asia premier industrial gathering. Live demonstrations of CNC robotics, metallurgy, smart factory automation, and heavy machine tools with 1,500 global exhibitors.',
    archetype: 'INDUSTRIAL_B2B',
    startDate: new Date('2026-09-14T09:00:00Z'),
    endDate: new Date('2026-09-17T18:00:00Z'),
    isFeatured: true,
    scale: 'LARGE',
    format: 'IN_PERSON',
    heroImageUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=1200',
    regionId: 'id',
    region: { id: 'id', code: 'ID', name: 'Indonesia', currency: 'IDR' },
    venueId: 'venue-jiexpo',
    venue: FALLBACK_VENUES[0],
    ticketTiers: [
      { id: 'tier-mfg-visitor', name: 'Trade Visitor Pass', price: 0, currency: 'IDR', capacity: 15000 },
      { id: 'tier-mfg-vip', name: 'VIP Procurement Buyer Pass', price: 450000, currency: 'IDR', capacity: 1200 },
      { id: 'tier-mfg-exhibitor', name: 'Exhibitor Delegate Pass', price: 1200000, currency: 'IDR', capacity: 3000 },
    ],
  },
  {
    id: 'event-ai-summit-2026',
    title: 'Asia AI & Cloud Developer Summit 2026',
    slug: 'asia-ai-summit-2026',
    tagline: 'Building Autonomous Multi-Agent Systems, LLMs & Next-Gen Cloud Infrastructure',
    description: 'Asia premier technical gathering for software engineers, AI researchers, and cloud architects with deep-dive keynotes, live code teardowns, and a 24-hour hackathon.',
    archetype: 'TECH_DEV_SUMMIT',
    startDate: new Date('2026-10-08T08:30:00Z'),
    endDate: new Date('2026-10-10T20:00:00Z'),
    isFeatured: true,
    scale: 'LARGE',
    format: 'HYBRID',
    heroImageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200',
    regionId: 'id',
    region: { id: 'id', code: 'ID', name: 'Indonesia', currency: 'IDR' },
    venueId: 'venue-ice',
    venue: FALLBACK_VENUES[1],
    ticketTiers: [
      { id: 'tier-ai-builder', name: 'Builder Pass', price: 250000, currency: 'IDR', capacity: 4000 },
      { id: 'tier-ai-vip', name: 'VIP Full Access & Speaker Dinner', price: 1250000, currency: 'IDR', capacity: 500 },
      { id: 'tier-ai-virtual', name: 'Virtual Livestream Pass', price: 0, currency: 'IDR', capacity: 20000 },
    ],
  },
  {
    id: 'event-prj-2026',
    title: 'Pekan Raya Jakarta (Jakarta Fair Kemayoran 2026)',
    slug: 'pekan-raya-jakarta-2026',
    tagline: 'The Largest & Longest-Running Consumer Mega Fair in Southeast Asia',
    description: 'Celebrate Jakarta anniversary with 33 consecutive days of mega consumer expositions, 500+ culinary tenants, massive automotive launches, nightly open-air concerts, and grand fireworks.',
    archetype: 'MEGA_EXPO_PAVILION',
    startDate: new Date('2026-06-10T10:00:00Z'),
    endDate: new Date('2026-07-12T23:00:00Z'),
    isFeatured: true,
    scale: 'GLOBAL_MEGA',
    format: 'IN_PERSON',
    heroImageUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1200',
    regionId: 'id',
    region: { id: 'id', code: 'ID', name: 'Indonesia', currency: 'IDR' },
    venueId: 'venue-jiexpo',
    venue: FALLBACK_VENUES[0],
    ticketTiers: [
      { id: 'tier-prj-entry', name: 'General Fair Entry (Non-Concert)', price: 40000, currency: 'IDR', capacity: 100000 },
      { id: 'tier-prj-concert', name: 'Fair Entry + Main Concert Pass', price: 100000, currency: 'IDR', capacity: 25000 },
      { id: 'tier-prj-vip', name: 'Season VIP Mega Pass (33 Days)', price: 650000, currency: 'IDR', capacity: 2500 },
    ],
  },

  // -------------------------------------------------------------------------
  // JAPAN EVENTS (JP)
  // -------------------------------------------------------------------------
  {
    id: 'event-tokyo-robotics-2026',
    title: 'Tokyo International Robotics & Mechatronics Expo 2026',
    slug: 'tokyo-robotics-expo-2026',
    tagline: 'Humanoid Robotics, Autonomous Mobility & Industrial AI Automation',
    description: 'The world foremost robotics exhibition held at Tokyo Big Sight East Halls. Discover breakthrough humanoid robots, collaborative arms, surgical mechatronics, and autonomous factory logistics.',
    archetype: 'TECH_DEV_SUMMIT',
    startDate: new Date('2026-11-18T10:00:00Z'),
    endDate: new Date('2026-11-21T17:00:00Z'),
    isFeatured: true,
    scale: 'LARGE',
    format: 'IN_PERSON',
    heroImageUrl: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=1200',
    regionId: 'jp',
    region: { id: 'jp', code: 'JP', name: 'Japan', currency: 'JPY' },
    venueId: 'venue-tokyo',
    venue: FALLBACK_VENUES[4],
    ticketTiers: [
      { id: 'tier-tokyo-gen', name: 'General Trade Pass', price: 3000, currency: 'JPY', capacity: 30000 },
      { id: 'tier-tokyo-vip', name: 'Executive Delegate & Lab Tour', price: 15000, currency: 'JPY', capacity: 2000 },
    ],
  },
  {
    id: 'event-japan-game-expo-2026',
    title: 'Tokyo Comic & Gaming Championship 2026',
    slug: 'tokyo-gaming-championship-2026',
    tagline: 'Esports Championship Arena, Indie Creator Alley & Anime Premieres',
    description: 'Japan premier digital entertainment festival at Makuhari Messe with world championship esports finals, voice actor panels, and massive merchandise booths.',
    archetype: 'POP_CULTURE_GAMING',
    startDate: new Date('2026-09-24T09:30:00Z'),
    endDate: new Date('2026-09-27T18:30:00Z'),
    isFeatured: true,
    scale: 'LARGE',
    format: 'IN_PERSON',
    heroImageUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1200',
    regionId: 'jp',
    region: { id: 'jp', code: 'JP', name: 'Japan', currency: 'JPY' },
    venueId: 'venue-makuhari',
    venue: FALLBACK_VENUES[5],
    ticketTiers: [
      { id: 'tier-jp-game-std', name: 'Standard Day Pass', price: 3500, currency: 'JPY', capacity: 50000 },
      { id: 'tier-jp-game-vip', name: 'VIP Fast-Pass & Creator Alley Meetup', price: 18000, currency: 'JPY', capacity: 3000 },
    ],
  },
  {
    id: 'event-japan-ev-mobility-2026',
    title: 'Japan Clean EV & Future Mobility Show 2026',
    slug: 'japan-ev-mobility-2026',
    tagline: 'Solid-State Battery Tech, Hydrogen Fuel Cells & Autonomous Driving',
    description: 'Leading mobility exhibition at Pacifico Yokohama with test drive circuits, hydrogen fuel cell reveals, and direct OEM procurement.',
    archetype: 'AUTOMOTIVE_MOBILITY',
    startDate: new Date('2026-10-28T09:00:00Z'),
    endDate: new Date('2026-10-31T17:00:00Z'),
    isFeatured: true,
    scale: 'LARGE',
    format: 'HYBRID',
    heroImageUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200',
    regionId: 'jp',
    region: { id: 'jp', code: 'JP', name: 'Japan', currency: 'JPY' },
    venueId: 'venue-pacifico',
    venue: FALLBACK_VENUES[6],
    ticketTiers: [
      { id: 'tier-jp-auto-trade', name: 'OEM Industry Pass', price: 5000, currency: 'JPY', capacity: 20000 },
      { id: 'tier-jp-auto-vip', name: 'VIP Test-Track & Executive Lounge', price: 25000, currency: 'JPY', capacity: 1500 },
    ],
  },

  // -------------------------------------------------------------------------
  // GLOBAL EVENTS (GLOBAL / GL)
  // -------------------------------------------------------------------------
  {
    id: 'event-singapore-fintech-2026',
    title: 'Global FinTech & Institutional Investment Summit 2026',
    slug: 'singapore-fintech-summit-2026',
    tagline: 'Cross-Border Capital, Sovereign Wealth & AI-Driven Asset Management',
    description: 'High-level financial assembly bringing together central bank governors, institutional investors, sovereign wealth funds, and leading fintech innovators at Marina Bay Sands.',
    archetype: 'FINANCE_INVESTOR',
    startDate: new Date('2026-11-04T09:00:00Z'),
    endDate: new Date('2026-11-06T18:00:00Z'),
    isFeatured: true,
    scale: 'LARGE',
    format: 'HYBRID',
    heroImageUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=1200',
    regionId: 'global',
    region: { id: 'global', code: 'GL', name: 'Global Hubs', currency: 'USD' },
    venueId: 'venue-mbs',
    venue: FALLBACK_VENUES[7],
    ticketTiers: [
      { id: 'tier-fintech-delegate', name: 'Executive Delegate Pass', price: 495, currency: 'USD', capacity: 2500 },
      { id: 'tier-fintech-vip', name: 'VIP Investor Deal-Room Pass', price: 1250, currency: 'USD', capacity: 400 },
    ],
  },
  {
    id: 'event-frankfurt-industry-2026',
    title: 'Frankfurt International Smart Factory & Heavy Machinery Expo 2026',
    slug: 'frankfurt-smart-factory-2026',
    tagline: 'Industry 4.0, Additive Manufacturing & Global Supply Chain Resilience',
    description: 'Europe premier industrial trade fair at Messe Frankfurt showcasing automated assembly lines, digital twin simulations, and high-precision CNC tooling.',
    archetype: 'INDUSTRIAL_B2B',
    startDate: new Date('2026-10-14T09:00:00Z'),
    endDate: new Date('2026-10-17T18:00:00Z'),
    isFeatured: true,
    scale: 'LARGE',
    format: 'IN_PERSON',
    heroImageUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=1200',
    regionId: 'global',
    region: { id: 'global', code: 'GL', name: 'Global Hubs', currency: 'USD' },
    venueId: 'venue-messe-frankfurt',
    venue: FALLBACK_VENUES[8],
    ticketTiers: [
      { id: 'tier-ff-trade', name: 'Trade Visitor 3-Day Pass', price: 120, currency: 'USD', capacity: 45000 },
      { id: 'tier-ff-vip', name: 'VIP Buyer Executive Lounge', price: 650, currency: 'USD', capacity: 2000 },
    ],
  },
  {
    id: 'event-london-energy-2026',
    title: 'London Global Clean Energy & Green Infrastructure Forum 2026',
    slug: 'london-clean-energy-2026',
    tagline: 'Offshore Wind, Carbon Capture & Sovereign Green Bond Financing',
    description: 'Flagship European energy summit at ExCeL London with ministerial roundtables, renewable grid developers, and climate investment funds.',
    archetype: 'ENERGY_INFRASTRUCTURE',
    startDate: new Date('2026-11-25T08:30:00Z'),
    endDate: new Date('2026-11-27T17:30:00Z'),
    isFeatured: true,
    scale: 'LARGE',
    format: 'HYBRID',
    heroImageUrl: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=1200',
    regionId: 'global',
    region: { id: 'global', code: 'GL', name: 'Global Hubs', currency: 'USD' },
    venueId: 'venue-excel-london',
    venue: FALLBACK_VENUES[9],
    ticketTiers: [
      { id: 'tier-lon-delegate', name: 'Summit Delegate Pass', price: 380, currency: 'USD', capacity: 3500 },
      { id: 'tier-lon-vip', name: 'VIP Ministerial & Gala Pass', price: 950, currency: 'USD', capacity: 500 },
    ],
  },
];

export const FALLBACK_BANNER_SLIDES: BannerSlide[] = [
  // -------------------------------------------------------------------------
  // INDONESIA BANNER SLIDES (ID)
  // -------------------------------------------------------------------------
  {
    id: 'slide-id-1',
    title: 'Manufacturing Indonesia & Automation Expo 2026',
    tagline: '36th International Machinery, CNC Tooling & Industrial Robotics Exhibition',
    slug: 'manufacturing-indonesia-2026',
    heroImageUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=1600',
    archetype: 'INDUSTRIAL_B2B',
    startDate: new Date('2026-09-14T09:00:00Z'),
    endDate: new Date('2026-09-17T18:00:00Z'),
    venueName: 'JIExpo Kemayoran',
    venueHallName: 'Hall A1-A3',
    cityName: 'Jakarta',
    regionCode: 'ID',
    format: 'IN_PERSON',
    scale: 'LARGE',
    minPrice: 0,
    currency: 'IDR',
    isFeatured: true,
  },
  {
    id: 'slide-id-2',
    title: 'Asia AI & Cloud Developer Summit 2026',
    tagline: 'Autonomous Multi-Agent Architectures, Edge LLMs & Cloud Engineering Keynotes',
    slug: 'asia-ai-summit-2026',
    heroImageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=1600',
    archetype: 'TECH_DEV_SUMMIT',
    startDate: new Date('2026-10-08T08:30:00Z'),
    endDate: new Date('2026-10-10T20:00:00Z'),
    venueName: 'ICE BSD City',
    venueHallName: 'Nusantara Hall 2',
    cityName: 'Tangerang',
    regionCode: 'ID',
    format: 'HYBRID',
    scale: 'LARGE',
    minPrice: 250000,
    currency: 'IDR',
    isFeatured: true,
  },
  {
    id: 'slide-id-3',
    title: 'Pekan Raya Jakarta (Jakarta Fair 2026)',
    tagline: '33 Days of Mega Consumer Exhibitions, 500+ Tenants & Nightly Live Concerts',
    slug: 'pekan-raya-jakarta-2026',
    heroImageUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1600',
    archetype: 'MEGA_EXPO_PAVILION',
    startDate: new Date('2026-06-10T10:00:00Z'),
    endDate: new Date('2026-07-12T23:00:00Z'),
    venueName: 'JIExpo Kemayoran',
    venueHallName: 'Open Space Arena',
    cityName: 'Jakarta',
    regionCode: 'ID',
    format: 'IN_PERSON',
    scale: 'GLOBAL_MEGA',
    minPrice: 40000,
    currency: 'IDR',
    isFeatured: true,
  },

  // -------------------------------------------------------------------------
  // JAPAN BANNER SLIDES (JP)
  // -------------------------------------------------------------------------
  {
    id: 'slide-jp-1',
    title: 'Tokyo International Robotics & Mechatronics Expo 2026',
    tagline: 'Next-Gen Humanoid Robots, Autonomous Mobility & Industrial AI at Tokyo Big Sight',
    slug: 'tokyo-robotics-expo-2026',
    heroImageUrl: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=1600',
    archetype: 'TECH_DEV_SUMMIT',
    startDate: new Date('2026-11-18T10:00:00Z'),
    endDate: new Date('2026-11-21T17:00:00Z'),
    venueName: 'Tokyo Big Sight',
    venueHallName: 'East Hall 1-3',
    cityName: 'Tokyo',
    regionCode: 'JP',
    format: 'IN_PERSON',
    scale: 'LARGE',
    minPrice: 3000,
    currency: 'JPY',
    isFeatured: true,
  },
  {
    id: 'slide-jp-2',
    title: 'Tokyo Comic & Gaming Championship 2026',
    tagline: 'Esports Championship Arena, Indie Creator Alley & Anime Premieres at Makuhari Messe',
    slug: 'tokyo-gaming-championship-2026',
    heroImageUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1600',
    archetype: 'POP_CULTURE_GAMING',
    startDate: new Date('2026-09-24T09:30:00Z'),
    endDate: new Date('2026-09-27T18:30:00Z'),
    venueName: 'Makuhari Messe',
    venueHallName: 'International Exhibition Hall 1-8',
    cityName: 'Chiba',
    regionCode: 'JP',
    format: 'IN_PERSON',
    scale: 'LARGE',
    minPrice: 3500,
    currency: 'JPY',
    isFeatured: true,
  },
  {
    id: 'slide-jp-3',
    title: 'Japan Clean EV & Future Mobility Show 2026',
    tagline: 'Solid-State Battery Tech, Hydrogen Fuel Cells & Autonomous Driving at Pacifico Yokohama',
    slug: 'japan-ev-mobility-2026',
    heroImageUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1600',
    archetype: 'AUTOMOTIVE_MOBILITY',
    startDate: new Date('2026-10-28T09:00:00Z'),
    endDate: new Date('2026-10-31T17:00:00Z'),
    venueName: 'Pacifico Yokohama',
    venueHallName: 'Exhibition Hall A-D',
    cityName: 'Yokohama',
    regionCode: 'JP',
    format: 'HYBRID',
    scale: 'LARGE',
    minPrice: 5000,
    currency: 'JPY',
    isFeatured: true,
  },

  // -------------------------------------------------------------------------
  // GLOBAL BANNER SLIDES (GLOBAL / GL)
  // -------------------------------------------------------------------------
  {
    id: 'slide-gl-1',
    title: 'Global FinTech & Institutional Investment Summit 2026',
    tagline: 'Cross-Border Capital, Sovereign Wealth & AI-Driven Asset Management at Marina Bay Sands',
    slug: 'singapore-fintech-summit-2026',
    heroImageUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=1600',
    archetype: 'FINANCE_INVESTOR',
    startDate: new Date('2026-11-04T09:00:00Z'),
    endDate: new Date('2026-11-06T18:00:00Z'),
    venueName: 'Marina Bay Sands Expo',
    venueHallName: 'Sands Expo Halls A-F',
    cityName: 'Singapore',
    regionCode: 'GL',
    format: 'HYBRID',
    scale: 'LARGE',
    minPrice: 495,
    currency: 'USD',
    isFeatured: true,
  },
  {
    id: 'slide-gl-2',
    title: 'Frankfurt Smart Factory & Heavy Machinery Expo 2026',
    tagline: 'Industry 4.0, Additive Manufacturing & Precision Tooling at Messe Frankfurt',
    slug: 'frankfurt-smart-factory-2026',
    heroImageUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=1600',
    archetype: 'INDUSTRIAL_B2B',
    startDate: new Date('2026-10-14T09:00:00Z'),
    endDate: new Date('2026-10-17T18:00:00Z'),
    venueName: 'Messe Frankfurt',
    venueHallName: 'Hall 11 & 12',
    cityName: 'Frankfurt am Main',
    regionCode: 'GL',
    format: 'IN_PERSON',
    scale: 'LARGE',
    minPrice: 120,
    currency: 'USD',
    isFeatured: true,
  },
  {
    id: 'slide-gl-3',
    title: 'London Global Clean Energy & Green Infrastructure Forum 2026',
    tagline: 'Offshore Wind, Carbon Capture & Green Bond Financing at ExCeL London',
    slug: 'london-clean-energy-2026',
    heroImageUrl: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=1600',
    archetype: 'ENERGY_INFRASTRUCTURE',
    startDate: new Date('2026-11-25T08:30:00Z'),
    endDate: new Date('2026-11-27T17:30:00Z'),
    venueName: 'ExCeL London',
    venueHallName: 'ICC Capital Hall',
    cityName: 'London',
    regionCode: 'GL',
    format: 'HYBRID',
    scale: 'LARGE',
    minPrice: 380,
    currency: 'USD',
    isFeatured: true,
  },
];
